# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5fc00f8868bdd5ace8bb972311aac43218223937bfde9854fce52d0bcfefe4081cf062cd6196a0ed8be6285331fea9ab6440574801a2425ec3af86c64149bc

test:
  secret_key_base: 1efc16a21040fd85504a3dca896e13dfbf550bd98d40cfcb330c8e02fd1df1472d0204781b9dafdb615da550ae145e215d1691841ae4df9e7ace37e0068f9bc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
